class SessionHandler:
    sessions = [
        "2023 Second Special Session",
        "2024 Regular Session",
        "2023 First Special Session",
        "2023 Regular Session",
        "2022 Third Special Session",
        "2022 Second Special Session",
        "2022 Regular Session",
        "2021 First Special Session",
        "2021 Regular Session",
        "2020 Second Special Session",
        "2020 Regular Session",
        "2020 First Special Session",
        "2019 Regular Session",
        "2018 Regular Session",
        "2017 Second Special Session",
        "2017 First Special Session",
        "2017 Regular Session",
        "2016 Regular Session",
        "2015 Regular Session",
        "2014 Regular Session",
        "2013 Special Session",
        "2013 Regular Session",
        "2012 Regular Session",
        "2011 Regular Session",
        "2010 Regular Session",
        "2009 Regular Session",
        "2008 Regular Session",
        "2007 Regular Session",
        "2006 Second Special Session",
        "2006 Regular Session",
        "2005 Special Session",
        "2005 Regular Session",
        "2004 Special Session",
        "2004 Regular Session",
        "2003 Regular Session",
        "2002 Regular Session",
        "2001 Special Session",
        "2001 Regular Session",
        "2012 Special Session",
        "2000 Regular Session",
        "1999 Special Session",
        "1999 Regular Session",
        "1998 Regular Session",
        "1997 Regular Session",
        "1996 Regular Session",
        "1995 Regular Session",
        "1994 Second Special Session",
        "1994 First Special Session",
        "1994 Regular Session",
        "1993 Regular Session"
    ]
    session_values = ["232X",
                      "2400",
                      "231X",
                      "2300",
                      "223X",
                      "222X",
                      "2200",
                      "211X",
                      "2100",
                      "202X",
                      "2000",
                      "201X",
                      "1900",
                      "1800",
                      "172X",
                      "171X",
                      "1700",
                      "1600",
                      "1500",
                      "1400",
                      "131X",
                      "1300",
                      "1200",
                      "1100",
                      "1000",
                      "0900",
                      "0800",
                      "0700",
                      "062X",
                      "0600",
                      "051X",
                      "0500",
                      "041X",
                      "0400",
                      "0300",
                      "0200",
                      "011X",
                      "0100",
                      "121X",
                      "0000",
                      "991X",
                      "9900",
                      "9800",
                      "9700",
                      "9600",
                      "9500",
                      "942X",
                      "941X",
                      "9400",
                      "9300"]

    def select_session(self):
        for i, (session, session_value) in enumerate(zip(self.sessions, self.session_values)):
            print(f"{i} - Session: {session}, Session Value: {session_value}")

        selected_option = int(input("Enter the number of your selected session: "))

        if 0 <= selected_option < len(self.session_values):
            selected_session_value = self.session_values[selected_option]
            print(f"Selected session value: {selected_session_value}")
            return selected_session_value
        else:
            print("Invalid choice. Please select a valid option.")
            return None
